<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://xmlns.oracle.com/beam" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="BAMServerConnection1_BAM_POC_Employee.xsd"/>
            <oracle-xsl-mapper:rootElement name="BAM_POC_EmployeeCollection" namespace="http://xmlns.oracle.com/beam"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="BAMServerConnection1_BAM_POC_Employee.xsd"/>
            <oracle-xsl-mapper:rootElement name="BAM_POC_EmployeeCollection" namespace="http://xmlns.oracle.com/beam"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON SEP 14 19:35:22 IST 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:BAM_POC_EmployeeCollection>
         <xsl:for-each select="/ns0:BAM_POC_EmployeeCollection/ns0:BAM_POC_Employee">
            <ns0:BAM_POC_Employee>
               <ns0:BEAM_ID>
                  <xsl:value-of select="ns0:BEAM_ID"/>
               </ns0:BEAM_ID>
               <ns0:DATAOBJECT_CREATED>
                  <xsl:value-of select="ns0:DATAOBJECT_CREATED"/>
               </ns0:DATAOBJECT_CREATED>
               <ns0:DATAOBJECT_MODIFIED>
                  <xsl:value-of select="ns0:DATAOBJECT_MODIFIED"/>
               </ns0:DATAOBJECT_MODIFIED>
               <xsl:if test="ns0:EMP_ID">
                  <ns0:EMP_ID>
                     <xsl:value-of select="ns0:EMP_ID"/>
                  </ns0:EMP_ID>
               </xsl:if>
               <xsl:if test="ns0:EMP_NAME">
                  <ns0:EMP_NAME>
                     <xsl:value-of select="ns0:EMP_NAME"/>
                  </ns0:EMP_NAME>
               </xsl:if>
               <xsl:if test="ns0:EMP_DESG">
                  <ns0:EMP_DESG>
                     <xsl:value-of select="ns0:EMP_DESG"/>
                  </ns0:EMP_DESG>
               </xsl:if>
            </ns0:BAM_POC_Employee>
         </xsl:for-each>
      </ns0:BAM_POC_EmployeeCollection>
   </xsl:template>
</xsl:stylesheet>